import os

CHAT_MODEL = os.getenv("CHAT_MODEL", "qwen2.5:7b")
EMBEDDING_MODEL = os.getenv("EMBEDDING_MODEL", "nomic-embed-text")

AUTO_SCAN_INTERVAL_SECONDS = 3600

MAX_CHUNK_SIZE = 1500
CHUNK_OVERLAP = 200

PER_DOCUMENT_VECTOR_TOP_K = 6
PER_DOCUMENT_KEYWORD_TOP_K = 6
PER_DOCUMENT_DIRECT_TOP_K = 2
PER_DOCUMENT_CONTEXT_LIMIT = 5

NEIGHBOR_WINDOW = 1
MAX_CONTEXT_CHUNKS_TOTAL = 14

EMBEDDING_BATCH_SIZE = 32