from .settings import *

CHAT_MODEL_NAME = CHAT_MODEL

EMBEDDING_MODEL_NAME = EMBEDDING_MODEL

KNOWLEDGE_FOLDER = KNOWLEDGE_BASE_FOLDER

MAX_CHUNK_SIZE_VALUE = MAX_CHUNK_SIZE

CHUNK_OVERLAP_VALUE = CHUNK_OVERLAP

AUTO_SCAN_INTERVAL = AUTO_SCAN_INTERVAL_SECONDS

MAX_CONTEXT_CHUNKS = MAX_CONTEXT_CHUNKS_TOTAL

EMBEDDING_BATCH = EMBEDDING_BATCH_SIZE

PER_DOC_VECTOR_TOP_K = PER_DOCUMENT_VECTOR_TOP_K

PER_DOC_KEYWORD_TOP_K = PER_DOCUMENT_KEYWORD_TOP_K

PER_DOC_DIRECT_TOP_K = PER_DOCUMENT_DIRECT_TOP_K

PER_DOC_CONTEXT_LIMIT = PER_DOCUMENT_CONTEXT_LIMIT

NEIGHBOR_CHUNKS = NEIGHBOR_WINDOW